apiVersion: v1
kind: Service
metadata:
  name: {{ template "paas-service.fullname" . }}
  labels:
    app: {{ template "paas-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "paas-service.name" . }}
